# -*- coding: utf-8 -*-
"""种子数据: 科室与检查须知。init_db.py 导入 SQLite。"""

DEPARTMENTS = [
 {"id": "fs", "name": "放射科", "floor": 1, "nav_node_id": "1f_poi_fangshe", "category": "检查",
  "intro": "X光、DR、CT、核磁共振(MRI)、胃肠造影等影像检查", "common_exams": "X光,CT,MRI,胃肠造影",
  "tips": "检查前去除金属饰品;体内有金属植入物请提前告知", "aliases": "拍片,照光,ct,核磁,mri,x光,影像,照片子"},
 {"id": "zyf", "name": "中药房", "floor": 1, "nav_node_id": "1f_poi_zyf", "category": "药房",
  "intro": "中草药调配与代煎服务", "common_exams": "", "tips": "代煎药请按约定时间取", "aliases": "中药,代煎,抓药"},
 {"id": "xyf", "name": "西药房", "floor": 1, "nav_node_id": "1f_poi_xyf", "category": "药房",
  "intro": "西药、口服药、外用药取药窗口", "common_exams": "", "tips": "缴费后凭处方取药,请核对姓名和药名", "aliases": "取药,拿药,药房,西药,取药窗口"},
 {"id": "grb", "name": "感染科(发热门诊)", "floor": 1, "nav_node_id": "1f_poi_grb", "category": "门诊",
  "intro": "发热、感染性疾病的独立诊区", "common_exams": "血常规,核酸",
  "tips": "发热患者请先到此就诊,与普通门诊分开", "aliases": "发烧,发热,发热门诊,感染"},
 {"id": "erke", "name": "儿科", "floor": 1, "nav_node_id": "1f_poi_erke", "category": "门诊",
  "intro": "14岁以下儿童常见病诊治", "common_exams": "血常规",
  "tips": "带好疫苗本和既往病历", "aliases": "孩子,小孩,儿童,宝宝,儿科"},
 {"id": "jzzs", "name": "急诊(诊室区)", "floor": 1, "nav_node_id": "1f_poi_jzzs", "category": "急诊",
  "intro": "24小时急诊内科、外科、妇科诊室", "common_exams": "急诊检验",
  "tips": "危重患者可走急诊入口优先抢救", "aliases": "急诊,急救,紧急,看急诊"},
 {"id": "zsys", "name": "注射室", "floor": 1, "nav_node_id": "1f_poi_zhushe", "category": "治疗",
  "intro": "肌肉注射、静脉注射", "common_exams": "", "tips": "注射后请按压针眼至不出血", "aliases": "打针,吊针,输液"},
 {"id": "cfy1", "name": "划价收费(1F)", "floor": 1, "nav_node_id": "1f_poi_cfy1", "category": "收费",
  "intro": "门诊费用缴纳、处方划价", "common_exams": "", "tips": "可用医保卡或手机支付", "aliases": "缴费,交费,收费,结账,付钱"},
 {"id": "jyk", "name": "检验科", "floor": 2, "nav_node_id": "2f_poi_jyk", "category": "检查",
  "intro": "抽血、血化验、大小便检验", "common_exams": "血常规,尿常规,肝肾功能,血糖",
  "tips": "抽血请早上空腹前往,报告一般1-2小时出", "aliases": "抽血,验血,化验,查血,血常规,验尿"},
 {"id": "wkmz", "name": "外科门诊", "floor": 2, "nav_node_id": "2f_poi_wkmz", "category": "门诊",
  "intro": "普外、创伤、缝合拆线等", "common_exams": "清创缝合",
  "tips": "外伤患者可先到急诊", "aliases": "外科,外伤,缝合,拆线,伤口"},
 {"id": "ckmz", "name": "产科门诊", "floor": 2, "nav_node_id": "2f_poi_ckmz", "category": "门诊",
  "intro": "孕期产检、建卡", "common_exams": "胎心监护,B超",
  "tips": "产检请带好母子手册", "aliases": "产科,产检,孕妇,怀孕,建档"},
 {"id": "fkmz", "name": "妇科门诊", "floor": 2, "nav_node_id": "2f_poi_fkmz", "category": "门诊",
  "intro": "妇科常见病诊治", "common_exams": "妇科B超,白带常规",
  "tips": "检查前请排空膀胱", "aliases": "妇科"},
 {"id": "mzss", "name": "门诊手术室", "floor": 2, "nav_node_id": "2f_poi_mzss", "category": "治疗",
  "intro": "门诊小手术", "common_exams": "", "tips": "手术当天需家属陪同", "aliases": "门诊手术,小手术"},
 {"id": "ssj", "name": "碎石机房", "floor": 2, "nav_node_id": "2f_poi_ssj", "category": "检查",
  "intro": "体外冲击波碎石", "common_exams": "泌尿系B超",
  "tips": "治疗前请多饮水", "aliases": "碎石,结石"},
 {"id": "cfy2", "name": "分层挂号收费(2F)", "floor": 2, "nav_node_id": "2f_poi_cfy", "category": "收费",
  "intro": "2楼挂号与收费窗口", "common_exams": "", "tips": "高峰期建议手机支付", "aliases": "挂号,缴费,收费"},
 {"id": "csk", "name": "超声科", "floor": 3, "nav_node_id": "3f_poi_csk", "category": "检查",
  "intro": "B超、彩超检查", "common_exams": "腹部B超,心脏彩超,妇科B超,泌尿系B超",
  "tips": "腹部B超需空腹;泌尿系和妇科B超需憋尿", "aliases": "b超,彩超,超声,b超室"},
 {"id": "kqk", "name": "口腔科", "floor": 3, "nav_node_id": "3f_poi_kqk", "category": "门诊",
  "intro": "牙齿治疗、拔牙、补牙", "common_exams": "口腔全景片",
  "tips": "高血压心脏病患者拔牙前请告知医生", "aliases": "牙科,牙齿,拔牙,补牙,口腔,洗牙"},
 {"id": "gnjc", "name": "功能检查中心", "floor": 3, "nav_node_id": "3f_poi_gnjc", "category": "检查",
  "intro": "心电图、肺功能等检查", "common_exams": "心电图,动态心电图,肺功能",
  "tips": "心电图检查前请安静休息5分钟", "aliases": "心电图,心电,肺功能"},
 {"id": "nkmz1", "name": "内科门诊(一区)", "floor": 3, "nav_node_id": "3f_poi_nkmz1", "category": "门诊",
  "intro": "呼吸、消化、心血管等内科常见病", "common_exams": "血常规,心电图",
  "tips": "慢性病复诊请带好病历和检查报告", "aliases": "内科,看病,开药"},
 {"id": "nkmz2", "name": "内科门诊(二区)", "floor": 3, "nav_node_id": "3f_poi_nkmz2", "category": "门诊",
  "intro": "内分泌、神经内科等内科常见病", "common_exams": "血糖,甲功",
  "tips": "糖尿病患者可空腹来查血糖", "aliases": "内科,内分泌,血糖,甲亢"},
 {"id": "ebhk", "name": "耳鼻喉科", "floor": 3, "nav_node_id": "3f_poi_ebhk", "category": "门诊",
  "intro": "耳、鼻、咽喉疾病诊治", "common_exams": "耳镜,鼻内镜",
  "tips": "耳痛耳鸣请尽早就诊", "aliases": "耳朵,鼻子,喉咙,咽喉,耳鼻喉,打鼾"},
 {"id": "yk", "name": "眼科", "floor": 3, "nav_node_id": "3f_poi_yk", "category": "门诊",
  "intro": "眼病诊治、验光", "common_exams": "视力检查,眼底检查",
  "tips": "查眼底可能需要散瞳,请不要开车前往", "aliases": "眼睛,视力,眼科,验光,近视"},
 {"id": "xhnj", "name": "消化内镜中心", "floor": 4, "nav_node_id": "4f_poi_xhnj", "category": "检查",
  "intro": "胃镜、肠镜检查", "common_exams": "胃镜,肠镜,无痛胃肠镜",
  "tips": "胃镜需空腹6小时以上;肠镜需提前清肠;无痛内镜需家属陪同", "aliases": "胃镜,肠镜,胃肠镜,内镜,做镜子,无痛胃镜"},
 {"id": "pfk", "name": "皮肤科", "floor": 4, "nav_node_id": "4f_poi_pfk", "category": "门诊",
  "intro": "皮肤病、过敏诊治", "common_exams": "皮肤镜,过敏原",
  "tips": "就诊前请勿涂抹药膏", "aliases": "皮肤,湿疹,过敏,皮炎,长痘,荨麻疹"},
 {"id": "pttc", "name": "普通体检中心", "floor": 4, "nav_node_id": "4f_poi_pttc", "category": "体检",
  "intro": "个人和团体健康体检", "common_exams": "常规体检套餐",
  "tips": "体检当天空腹并携带身份证", "aliases": "体检,健康检查,入学体检"},
 {"id": "zyk", "name": "中医门诊", "floor": 4, "nav_node_id": "4f_poi_zyk", "category": "门诊",
  "intro": "中医辨证、针灸、推拿", "common_exams": "",
  "tips": "调理类就诊建议上午来", "aliases": "中医,调理,针灸,推拿,拔罐"},
 {"id": "kftt", "name": "康复疼痛门诊", "floor": 4, "nav_node_id": "4f_poi_kftt", "category": "门诊",
  "intro": "颈肩腰腿痛、术后康复", "common_exams": "",
  "tips": "康复治疗需按疗程进行", "aliases": "康复,疼痛,理疗,腰痛,颈椎"},
 {"id": "zlmz", "name": "肿瘤门诊", "floor": 4, "nav_node_id": "4f_poi_zlmz", "category": "门诊",
  "intro": "肿瘤咨询与随访", "common_exams": "",
  "tips": "复诊请带齐影像和病理资料", "aliases": "肿瘤,化疗,复查"}
]

EXAM_PREP = [
 {"id": "cxblood", "keywords": "抽血,验血,查血,血常规,生化,血糖,肝肾,肝功,肾功,甲功,凝血", "exam_name": "抽血化验", "fasting": 1, "duration": "约5分钟",
  "prep_text": "抽血前需空腹8-12小时(可少量饮水),当天早上不要吃早餐;穿宽松袖子的衣服;抽血后按压针眼3-5分钟,当天不要提重物"},
 {"id": "bchao_ab", "keywords": "腹部B超,肝胆B超,肝胆胰脾,上腹B超", "exam_name": "腹部B超", "fasting": 1, "duration": "约10分钟",
  "prep_text": "检查前空腹8小时,前一天晚餐吃清淡食物"},
 {"id": "bchao_ur", "keywords": "泌尿系B超,妇科B超,子宫B超,膀胱B超,憋尿,输尿管B超", "exam_name": "泌尿系/妇科B超", "fasting": 0, "duration": "约10分钟",
  "prep_text": "检查前1小时饮水500-800毫升,憋尿至有明显尿意再检查"},
 {"id": "weijing", "keywords": "胃镜,无痛胃镜,上消化道内镜", "exam_name": "胃镜", "fasting": 1, "duration": "约15分钟",
  "prep_text": "检查前禁食6-8小时;前一天晚餐吃清淡易消化食物;无痛胃镜需家属陪同,检查后当天不要开车"},
 {"id": "changjing", "keywords": "肠镜,结肠镜,清肠", "exam_name": "肠镜", "fasting": 1, "duration": "约30分钟",
  "prep_text": "检查前一天进流食,按医嘱服用清肠药;检查当天禁食;无痛肠镜需家属陪同"},
 {"id": "xinguang", "keywords": "心电图,动态心电,心电", "exam_name": "心电图", "fasting": 0, "duration": "约5分钟",
  "prep_text": "检查前安静休息5分钟,避免剧烈运动和情绪激动,上身不要穿化纤衣服"},
 {"id": "ct", "keywords": "ct,增强ct", "exam_name": "CT", "fasting": 0, "duration": "约10分钟",
  "prep_text": "去除检查部位的金属物品;增强CT需空腹并做碘过敏皮试"},
 {"id": "mri", "keywords": "mri,核磁,磁共振", "exam_name": "核磁共振(MRI)", "fasting": 0, "duration": "约20分钟",
  "prep_text": "严禁携带任何金属进入;体内有心脏起搏器、金属植入物、金属假牙须提前告知医生;检查声音较大属正常"},
 {"id": "xguang", "keywords": "x光,拍片,dr,胸片,放射,透视", "exam_name": "X光/拍片", "fasting": 0, "duration": "约5分钟",
  "prep_text": "去除检查部位的金属饰品和纽扣;已怀孕或可能怀孕请提前告知医生"}
]


MEDICINE_GUIDE = [
 {"id": "before_meal", "category": "服药时间", "title": "饭前服药",
  "content": "饭前30-60分钟服用,吸收更好。常见的胃药、降糖药多为饭前服,具体以医嘱和说明书为准"},
 {"id": "after_meal", "category": "服药时间", "title": "饭后服药",
  "content": "饭后15-30分钟服用,可减少胃部刺激。对胃有刺激的药(如阿司匹林、布洛芬)一般饭后服"},
 {"id": "empty_stomach", "category": "服药时间", "title": "空腹服药",
  "content": "指早上起床后或两餐之间(饭前1小时/饭后2小时)服用,吸收最好"},
 {"id": "missed", "category": "用药安全", "title": "漏服了怎么办",
  "content": "一般想起时立即补服;若已接近下次服药时间,就跳过这一次,千万不要一次吃双份"},
 {"id": "children", "category": "儿童用药", "title": "儿童用药注意",
  "content": "严格按体重或年龄计算剂量;不要把成人药掰开给孩子吃;可用喂药器辅助,服药后竖抱拍嗝"},
 {"id": "storage", "category": "用药安全", "title": "药品保存",
  "content": "常温、避光、干燥处保存;需冷藏的放冰箱冷藏室(不是冷冻);过期药不要服用"},
 {"id": "course", "category": "用药安全", "title": "按疗程服药",
  "content": "症状好转也要吃完整个疗程,尤其是抗生素,不要自行停药,否则容易反复或产生耐药"},
 {"id": "liquid", "category": "剂型说明", "title": "冲剂和口服液",
  "content": "冲剂用温水冲开搅匀后服用;口服液用量杯量准剂量;混悬液服用前先摇匀"}
]

DOCTORS_DEMO = [
 {"id": "doc01", "name": "王建国", "dept_id": "nkmz1", "title": "主任医师", "schedule_text": "周一/三/五 上午", "intro": "擅长高血压、冠心病、糖尿病等慢性病诊治"},
 {"id": "doc02", "name": "李慧", "dept_id": "nkmz2", "title": "副主任医师", "schedule_text": "周二/四 全天", "intro": "擅长内分泌疾病、甲状腺疾病"},
 {"id": "doc03", "name": "张伟", "dept_id": "wkmz", "title": "主任医师", "schedule_text": "周一至周五 上午", "intro": "擅长普外科常见病、外伤处理"},
 {"id": "doc04", "name": "陈静", "dept_id": "erke", "title": "主任医师", "schedule_text": "周一/二/四 全天", "intro": "擅长儿童呼吸道疾病、消化道疾病"},
 {"id": "doc05", "name": "刘芳", "dept_id": "fkmz", "title": "副主任医师", "schedule_text": "周三/五 全天", "intro": "擅长妇科常见病、妇科炎症"},
 {"id": "doc06", "name": "赵敏", "dept_id": "ckmz", "title": "主治医师", "schedule_text": "周一至周五 上午", "intro": "擅长孕期产检、高危妊娠管理"},
 {"id": "doc07", "name": "孙强", "dept_id": "kqk", "title": "主治医师", "schedule_text": "周二/四/六 上午", "intro": "擅长牙齿治疗、拔牙、补牙"},
 {"id": "doc08", "name": "周琳", "dept_id": "pfk", "title": "主治医师", "schedule_text": "周一/三 全天", "intro": "擅长湿疹、过敏性皮炎、荨麻疹"},
 {"id": "doc09", "name": "吴德发", "dept_id": "zyk", "title": "副主任医师", "schedule_text": "周二/五 上午", "intro": "擅长中医调理、针灸推拿"},
 {"id": "doc10", "name": "郑海", "dept_id": "ebhk", "title": "主治医师", "schedule_text": "周一/四 全天", "intro": "擅长鼻炎、咽喉炎、中耳炎"}
]


# 爬虫科室名 -> 系统科室 id; 映射为 None 的是不出门诊的平台科室, 不进挂号演示
DEPT_CRAWL_MAP = {
 "口腔科": "kqk", "超声科": "csk", "放射科": "fs",
 "耳鼻咽喉头颈外科": "ebhk", "眼科": "yk", "皮肤科(美容皮肤科)": "pfk",
 "血液与肿瘤科": "zlmz",
 "心血管内科": "nkmz1", "消化内科": "nkmz1", "呼吸与危重症医学科": "nkmz1",
 "肾脏与风湿免疫病科": "nkmz1",
 "神经内科": "nkmz2", "内分泌代谢病科": "nkmz2", "老年医学科(国际医学中心)": "nkmz2",
 "儿科": "erke", "新生儿科": "erke",
 "妇科": "fkmz", "产科": "ckmz",
 "普通外科(中西医结合外科)": "wkmz", "泌尿外科": "wkmz", "整形美容外科": "wkmz",
 "关节创伤科": "wkmz", "脊柱骨病科": "wkmz", "神经外科": "wkmz",
 "胸外科": "wkmz", "肝胆外科": "wkmz", "心血管外科": "wkmz",
 "感染性疾病科": "grb", "急诊科": "jzzs",
 "检验科": "jyk", "康复医学科": "kftt", "体检科": "pttc", "中医科": "zyk",
 "麻醉科": None, "病理科": None, "输血科": None, "手术室": None, "药学部": None,
 "临床营养科": None, "高压氧科": None, "门诊部": None, "重症医学科": None,
 "临床心理科": None,
}
